# TODO: requires additional manual build outside! `CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python==0.3.4 --upgrade --force-reinstall --no-cache-dir`
name: onset
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12.8
  - pip
  - cuda #=12.4.1
  - cuda-toolkit #=12.4.1
  - cuda-runtime #=12.4.1
  - cuda-libraries-dev
  - cuda-libraries
  - cudnn
  #- cudatoolkit
  #- cudatoolkit-dev
  #- cuda-cudart-dev
  - compilers
  - postgresql
  - postgis
  - pgvector
  - pip:
    - fastapi[standard]
    - python-multipart
    - pandas
    - numpy
    - networkx
    - pyvis
    - rdflib[networkx,html,lxml,orjson]
    - psycopg[binary]
    - sentence-transformers
    - SQLAlchemy
    - sqlmodel
    - torch
    - transformers
    - bertopic
    - pgvector
    - cachetools
    - redis-om
    - llvmlite>=0.44.0
    - seqeval
    - sparql-llm>=0.0.3
    - langchain>=0.3.14
    - langchain-huggingface>=0.1.2
    - langchain-community>=0.3.14
    - qlever>=0.5.15
    - qdrant-client>=1.13.0
    - sparqlwrapper>=2.0.0
    - openai>=1.59.9
    - line-profiler>=4.2.0
    - llama-cpp-agent
